### ISSUE TITLE
ToDo: Toms

### ISSUE THREAD

**Issue by elvis-egle** [azeroc/lu_df_osk_disk_scheduling#2]
Vajag pielikt radio pogas ar būltiņām, kas pasaka uz kuru pusi iet adatai: pa kreisi - 0; pa labi - 1

**Comment by azeroc** [comment]
Ieliku radio pogas, kurām ir vērtības "right" (noklusētais variants) un "left", kuras tiek ieliktas "direction" atslēgā iekš getConfigData() atgrieztā objekta:
https://github.com/azeroc/lu_df_osk_disk_scheduling/commit/6b965c3cd896e28ae1a6d8fdffd8fefcfe6f4753
