### ISSUE TITLE
Algoritmu izvēlne

### ISSUE THREAD

**Issue by uldislazdins** [azeroc/lu_df_osk_disk_scheduling#3]
Ienāca prātā doma, ka tomēr varētu iešmaukt algoritmu izvēlni. Kaut kādu checkbox-dropdown kontroli, ja tāda ir iekš Bootstrap. Pašlaik dažus algoritmus ir grūti atšķirt, jo to ģenerētās līnijas pārklājas. Bija doma ieviest mazu offset līnijām - ko arī izdarīšu -, bet tas tā pat nenovērsīs clusterfuck, kas veidosies pie garām rindām un eksotiskām vērtībām.

**Comment by azeroc** [comment]
https://github.com/azeroc/lu_df_osk_disk_scheduling/commit/82bd3db1eb039ab9917c97f7e90711e18b368dfe
